export const notificationConstants = {
	ADD_NOTIFICATION: 'ADD_NOTIFICATION',
	CLOSE_NOTIFICATION_POPUP: 'CLOSE_NOTIFICATION_POPUP',
	FETCH_NOTIFICATIONS_REQUEST: 'FETCH_NOTIFICATIONS_REQUEST',
	FETCH_NOTIFICATIONS_SUCCESS: 'FETCH_NOTIFICATIONS_SUCCESS',
	READ_NOTIFICATIOS: 'READ_NOTIFICATIOS',
	TOGGLE_NOTIFICATION_POPUP: 'TOGGLE_NOTIFICATION_POPUP',
}
